export const REQUEST_AUTH = "REQUEST_AUTH"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT = "LOGOUT"
export const CLEAR_ERROR = "CLEAR_ERROR"